### ISSUE TITLE
Word not highlighted after dot (".")

### ISSUE THREAD

**Issue by tarobun** [cser/typewriter-net#13]
Not sure if this is a bug but in Kate word after the "." is highlighted in color while in TypeWriter.NET it is black (uncolored). This is for a *.cs file.

eg.

	public Controller(LineArray lines)
	{
		this.lines = lines;
		this.selections = lines.selections;
		lines.viStoreSelector = this;
		processor = new CommandProcessor(this, lines, selections);
		processor.ResetCommandsBatching();
	}

lines, selections viStoreSelector and ResetCommandsBatching are colored in Kate.

**Comment by cser** [comment]
It's expected behaviour, c# was modified for highlight types, and I remove highlighting after "."
Variants:
- I show apathy - change it for all and override it in my setup only by "Preferences/Edit current syntax file"
- Show more apathy and dont override in my setup :)
- Add switch logic - to make possible all users to use both highlightings (haven't idea how it must works - it's a configuration problem of old Kate syntaxes)
- Make special style "dsAfterDot" and special color schemes, that don't colorize it - seems to be overhead

Do you like the highlighting after "." or you just thought it was a bug?
(I just have no idea what users like)

**Comment by cser** [comment]
If you want to see old version _right now_, press "Edit current syntax" and replace text by this:
https://github.com/cser/typewriter-net/blob/62c9b32548b1cd366c0e44f4a2444ad637047f07/TypewriterNET/bin/syntax/cs.xml

There no Type highlihting

**Comment by cser** [comment]
But anyway, we need a mechanism to change the priority of syntax files. I try to add special parameter to config

**Comment by cser** [comment]
Now you can use to enable old syntax
`<item name="syntax:*.cs" value="c#-old"/>`
Implementation of parameter "syntax" was needed by any case
But I still have questions:
- Are you really want old-c# version, or it was mistake, may be remove it? (by default uses c#, i.e. I don't care)
- Is wanted to add types highlighting in c#-old?

**Comment by tarobun** [comment]
The more colors the better! I thought the cs.xml file was the same as kate's so thought it might be a bug. Didn't realize you had changed it. 

I have now update my cs.xml to do both types of highlighting, so I guess add types highlighting to c#-old?

**Comment by cser** [comment]
Yes, please add types hilghting to c#-old
- may be left name c#-old
- may be name it "c#-more-colors"
- may be set your c# by default and name my less-colored syntax as "c#-old" or "c#-less-colored"
I don't know how it should be, all 3 versions are acceptable

**Comment by tarobun** [comment]
Since the changes are just 4 additional lines to cs.xml maybe add to that? Or would you prefer the default not to have highlighting after the dot?

**Comment by cser** [comment]
I don't know what would be better >_<
1. Change c#, add с#-less-colors
2. Don't change c#, add c#-more-colors
Do as you wish - you are representative of the users of this editor

**Comment by cser** [comment]
or just add this 4 lines in c#, then I make c#-less-colors - it does not require a lot of my time

**Comment by tarobun** [comment]
I've added to c# - see if you like it. If not, it would be good to have some way to specify default.
