### ISSUE TITLE
Two "Untitled.txt" tabs can be opened at the same time.

### ISSUE THREAD

**Issue by tarobun** [cser/typewriter-net#4]
Steps to reproduce:
1. Start Typewriter.NET 
2. Select "File | New"
3. Two tabs are open called "Untitled.txt"

Note: If you select "File | New" again, you don't get another tab...

**Comment by cser** [comment]
It's intentional behaviour: creation of new Untitled.txt is prevented until previous has no changes

**Comment by cser** [comment]
In General, it is necessary to revise this logic

**Comment by cser** [comment]
Now several Untitled.txt can be opened
