### ISSUE TITLE
Find/Replace dialog not very intuitive

### ISSUE THREAD

**Issue by tarobun** [cser/typewriter-net#5]
The Find/Replace functionality is not very user friendly....

Steps
1) Open the Find/Replace dialog (Ctrl+H)
2) Enter some text to find and hit enter.
3) "Text" is found and highlighted in editor.
4) Hit tab to move to replace textbox. (btw: Shift+Tab doesn't tab to previous control)
5) Enter text to replace and hit enter.
6) Editor moves to next found text. 

Expected
6. Editor replaces highlighted text with new text.

How do you replace text?.... Hit Ctrl+Shift+H!?
Replace all text?... Hit Ctrl+Alt+Enter!?

How did I know that? By looking at the code!....

**Comment by cser** [comment]
Yeah, it's not most obvious thing in editor. I'll try to do something with it.

"How did I know that? By looking at the code!...." - By pressing Ctrl+Shift+P when inside dialog or open menu

P.S. Have you any idea how to talk user about keys for modes i, r switching? Or just write in help "In any strange situation press Ctrl+Shift+P"?

**Comment by cser** [comment]
I have problem with it: It works as in Sublime Text (and shortcut is equal)
I tried see to Notepad++, but it don't replace on enter too and I can't find shortcuts for replace - only button
- What kind of editor replace text by Enter?
- May be just add a similarity of the buttons [Replace] [Replace All]?

**Comment by cser** [comment]
Ctrl+Tab in Notepad and Subime do the same that Tab do
- Is duplication of shortcut Tab by Ctrl+Tab needed? (just for habit)

**Comment by tarobun** [comment]
Any visible/obvious method for initiating a replace/replace all text is all that is needed.
[Replace] [Replace All] would be perfect.

Not sure the reference to Tab is about. I just mentioning that in the replace dialog hitting [Tab] moves the focus to the next field (which is standard Windows behaviour), but the standard [Shift+Tab] does not move the focus back to the previous field.

I always wondered what the [i] [r] [e] characters meant.... finally worked it out, but I think a tooltip or something would definitely help.

**Comment by cser** [comment]
Buttons and hints added. Ctrl+Tab shortcat for ReplaceDialog added. Now seems to be cleaner
