### ISSUE TITLE
Issue with replace text

### ISSUE THREAD

**Issue by tarobun** [cser/typewriter-net#6]
Steps.
1) Enter the word "test" on lines 1-9.
2) Go to start of line 5.
3) Hit Ctrl+D x 3 (multi-select "test" on lines 5-7)
4) Hit Ctrl+H
5) Enter replace text "pass"
6) Hit Ctrl+Shift+H x 7

Output:
pass
pass
pass
pass
passpasspasspasspasspasspass
passpasspasspasspasspasspass
pass
pass
pass

Expected:
pass
pass
pass
pass
pass
pass
pass
pass
pass

**Comment by cser** [comment]
I accept it, just fix other bugs at first

**Comment by cser** [comment]
Fixed
