### ISSUE TITLE
Words with certain symbol prefixes not being highlighted

### ISSUE THREAD

**Issue by tarobun** [cser/typewriter-net#8]
1. Enter the following in a new file:
```
`test
~test
!test
@test
#test
$test
%test
^test
&test
*test
(test
)test
_test
-test
+test
=test
<test
>test
?test
/test
:test
;test
'test
[test
]test
{test
}test
\test
|test
test
```

2. Highlight/Double-click the word "test" 

Actual:
The following "test" words are not highlighted.
```
`test
@test
#test
$test
_test
```

Expected:
All "test" words to be highlighted.

**Comment by cser** [comment]
Fixed, except '_' - it can be start of identifier and more expected logic is to highlight word "_test" separately from "test". They are 2 different identificators in most popular languages
